#
batch_size: 1
seq_len: 20
epochs: 100
update_interval: 1
accumulate_grad_batches: 64

img_size:
  w: 1280
  h: 720
  resize_ratio: 0.5

autoencoder:
  i3d:
    final_endpoint: Mixed_3c
    # NOTE: Below params are defined by final_endpoint.
    #       Check the output shape before set.
    nch: 480  # output channel
    seq_len: 10  # output length
    # fx: 80  # output width
    # fy: 45  # output height
  nch: 24

clustering:
  n_clusters: 15
  ndf: 32
  alpha: 2  # freedom of student T
  roialign:
    output_size: 5
    spatial_scale: 0.125
    aligned: True
  add_spacial_feature: True

optim:
  lr_rate_ae_frame: 0.0001
  lr_rate_ae_flow: 0.0001
  lr_rate_cm: 0.0001
  lmd_cm: 10
