batch_size: 1
seq_len: 20
resize_ratio: 0.5
epochs: 200
clustering_start_epoch: 101
update_interval: 1
accumulate_grad_batches: 64

img_size:
  w: 1280
  h: 720

autoencoder:
  i3d:
    final_endpoint: Mixed_3c
  ndf: 32

clustering:
  n_clusters: 9  # waiting, setting, digging, failing, spiking, blocking, jumping, moving, standing
  ndf1: 256  # decoder
  ndf2: 32  # decoder
  alpha: 1  # freedom of student T
  roialign:
    output_size: 5
    spatial_scale: 0.125
    aligned: True

optim:
  lr_rate_ae: 0.0001
  lr_rate_cm: 0.0001
  lmd_cm: 10
