batch_size: 1
seq_len: 20
epochs: 200
accumulate_grad_batches: 512

img_size:
  w: 1280
  h: 720
  resize_ratio: 0.5

autoencoder:
  i3d:
    final_endpoint: Mixed_3c
    # NOTE: Below params are defined by final_endpoint.
    #       Check the output shape before set.
    nch: 480  # output channel
    # seq_len: 10  # output length
    # fx: 80  # output width
    # fy: 45  # output height
  nch: 24

optim:
  lr: 0.0001
