batch_size: 1
seq_len: 20
# epochs: 120
# clustering_start_epoch: 21
epochs: 100
accumulate_grad_batches: 16

img_size:
  w: 720
  h: 480
  resize_ratio: 1.0

autoencoder:
  i3d:
    final_endpoint: Mixed_3c
  ndf: 16

clustering:
  n_clusters: 6  # nonaction, crossing, waiting, queueing, walking, talking
  ndf1: 1024
  ndf2: 32
  alpha: 4  # freedom of student T
  roialign:
    output_size: 7
    spatial_scale: 0.125
    aligned: True

optim:
  lr_rate_ae_frame: 0.0001
  lr_rate_ae_flow: 0.0001
  lr_rate_cm: 1
  lmd_cm: 100
